### PR TITLE
Display PPCs where appropriate

### LINKED ISSUE #351: Display prospective parliamentary candidates for 2025 constituencies
PPCs won’t appear in the Democracy Club API until an election date is announced, but in the meantime, they’ve shared preliminary data, which seems to come straight from the Google Sheet their volunteers are maintaining:

https://whocanivotefor.co.uk/ppcs/details/

- [x] Update current (WMC) area page to pull in MPs specifically
- [x] Write import script for DC PPCs – create Person objects with "candidate" type, associated with the new (WMC23) constituencies – for now, don’t do anything clever about "reusing" existing Person objects for existing MPs, just create a new Person object for each PPC.
- [ ] Update new (WMC23) area page to display PPCs

### PR DESCRIPTION
**Pull request by struan**
Fixes #351

### CODE REVIEW

**Comment by alexander-griffen** [comment]
Added this to the appropriate area pages:
image

**Comment by zarino** [comment]
@alexander-griffen quick question! Do you think we’d be able to get the candidate’s photo (if it exists) from the Democracy Club source too? eg: https://whocanivotefor.co.uk/person/6042

**Review by zarino — COMMENTED** [review]
Given the area page markup/styling is all about to get changed in #349, I’m not that bothered about the new markup here. Seems fine for now.

We’ll need to wait for @struan to get back, to review the rest of this before merging and deploying.

**Comment by struan** [comment]
FWIW I've updated the display on this to look like:

Screenshot 2024-01-11 at 11 56 14

And created a ticket for the photos: https://github.com/mysociety/local-intelligence-hub/issues/379

**Comment by zarino** [comment]
@struan – looks good, I’ve added a `card-footer` to the cards, which credits Democracy Club.

**Pull request merged**
