### PR TITLE
postcode/mp/area lookup on front page

### PR DESCRIPTION
**Pull request by struan**
Place/MP/Postcode search on homepage now works. With a disambiguation page when you enter a search term that matches multiple places or MPs:

Screenshot 2022-11-03 at 16-17-36 Screenshot

### CODE REVIEW

**Review by alexander-griffen — APPROVED** [review]
Looks good and works!

Only question is (and I'm not sure if this is a feature or a bug), when I'm using firefox the 'Use my location' doesn't show up (and when inspecting it, 
```
<a class="js-geolocate d-none d-flex align-items-center btn btn-link px-0" href="{% url 'area_search' %}">
                    {% include 'hub/includes/icons/geolocate.html' with classes="me-2" %}
                    Use my current location
</a>
```
is greyed out), however it does show up - and work - on Safari.

**Comment by zarino** [comment]
@alexander-griffen interesting! So once the page has finished loading, the link still has its `d-none` class? If so, then `    if( 'geolocation' in navigator )` must be returning false on your machine. I would have guessed it might be because you’re accessing the site under `http://` rather than `https://` (geolocation only works under `https://`) – but since it works in Safari, and Safari (version 10+) requires https for geolocation too, I’m not sure what might be going on 🤔

**Comment by alexander-griffen** [comment]
@zarino 

Yep, it still has that class. I had a look through my Firefox settings to see if I'd unwittingly set something to prevent geolocation things from showing up, but I can't find any. I did find a https-only setting, which I turned on, and still can't get it to show up.

**Comment by zarino** [comment]
In fact, I’ve just tried it myself, and realised I was getting confused with the Jekyll prototypes, and I’ve never actually tried to access this version of the site over https://, I’ve just been using http:// and of course, the geolocation button remains hidden. And from the look of it, the built-in Django `runserver` development server doesn’t support serving over SSL anyway. Sigh.

**Pull request merged**
